" Lion's personal vimrc. More advanced settings are stored in files in the
" settings subfolder. Every .vim file in there will be automatically sourced.
"
" REQUIREMENTS: Symlink this file to ~/.vimrc and its parent folder to ~/.vim
" Necessary so everything can be found and no absolute paths are necessary.


" Use vim settings instead of vi settings. MUST be the first thing in the
" vimrc.
set nocompatible


" =============================================================================
" ========= Pathogen initialization
" Use pathogen to load all other plugins. Automatically loads all plugins in
" the bundle subfolder.
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
" Generate documentation for all plugins in the bundle subfolder.
call pathogen#helptags()


" =============================================================================
" ========== General configuration
let mapleader=","               " change the leader key to colon. Much easier
				" to reach than the standard backslash.
set t_Co=256                    " Enable 256 color in vim.
set laststatus=2                " Always show the statusline.
set encoding=utf-8              " Usually necessary to show unicode glyphs.
set hidden                      " Enable hidden buffers. Basically enables
				" buffer switching without saving first.
syntax on 			" Enable syntax highlighting.
set updatetime=1000 		" Update time of many VIM things. Seems a
				" reasonable value.


set cursorline          " show the cursor line
set cursorcolumn        " show the cursor column


" Autodetect filetype and necessary for some other stuff to work.
filetype plugin on
filetype plugin indent on
filetype on
filetype indent on


" =============================================================================
" ==========  Color scheme
" Use the light variant of the scheme if possible. This is in my experience
" quite a bit easier to read under direct sunlight.
set background=light
" Use the solarized colorscheme: http://ethanschoonover.com/solarized
" Take care that your terminal uses the same colorscheme so everything looks
" nice and consistent.
colorscheme solarized


" =============================================================================
" ========== Magic happening behind the scenes
" Automatically remove all trailing whitespace upon saving the current buffer.
autocmd BufWritePre * :%s/\s\+$//e
" All yanking and pasting works with the actual system clipboard. Does not
" work with all vim version but other ways to achieve this behaviour also
" exist and will be added if necessary.
set clipboard=unnamed


" =============================================================================
" ==========  Syntax highlighting
" Recognize GLSL files based on the extension name.
au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl setf glsl


" =============================================================================
" ========== Load all other settings stored in their own files in the settings
" ========== subfolder
for f in split(glob('~/.vim/settings/*.vim'), '\n')
    exe 'source' f
endfor
